server:
  port: 8080
  servlet:
    context-path: /learning-english

spring:
  datasource:
    url : "jdbc:mysql://192.168.122.179:3306/learning_english"
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "h0/nCC1lkSCu1Jzmf+p6JPFw29k7yC3+yH9XchTFL+5/S8zSMmSDlpY5IF50bYMR"